name: Package Project

# kiedy mam uruchomic automatyzacje
on: [ push ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # pobierz kod
      - uses: actions/checkout@v3
      # moja aplikacja jest w Pythonie
      - name: Set up Python 3
        uses: actions/setup-python@v3
      # instalacja wymaganych bibliotek
      - name: Install deps
        run: make deps
      # testy!!!!!
      - name: Tests
        run: make test
      - name: Build Image
        run: make docker_build
      - name: Run Docker
        run: make docker_run
  docker:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: szymon7907/test:1.3.0